CREATE SCHEMA chat;

CREATE TABLE chat.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1),
    username varchar(255),
    password varchar(255),
    name varchar(255),
    disabled boolean NOT NULL default false,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE chat.roles
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1),
    name varchar(10),
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE chat.user_roles
(
    users_id integer NOT NULL,
    roles_id integer NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (users_id, roles_id),
    CONSTRAINT user_roles_fkey_role FOREIGN KEY (roles_id) REFERENCES chat.roles(id) ON DELETE RESTRICT,
    CONSTRAINT user_roles_fkey_user FOREIGN KEY (users_id) REFERENCES chat.users(id) ON DELETE CASCADE
);

CREATE TABLE chat.messages
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1),
    content varchar(2000),
    send_date timestamp without time zone,
    type varchar(10),
    receiver_id int,
    user_id int NOT NULL,
    CONSTRAINT messages_pkey PRIMARY KEY (id),
    CONSTRAINT messages_fkey_user FOREIGN KEY (user_id) REFERENCES chat.users(id) ON DELETE CASCADE,
    CONSTRAINT messages_fkey_receiver FOREIGN KEY (receiver_id) REFERENCES chat.users(id) ON DELETE SET NULL
);

